// Generated by CoffeeScript 1.12.4
(function() {
  var controller, util;

  util = require('util');

  controller = {};

  controller.index = function(req, res) {
    return res.json("this is the /hello index, available functions are hello, foo/VARIABLE, test");
  };

  controller.hello = function(req, res) {
    return res.json("hello world from API");
  };

  controller.foo = function(req, res) {
    return res.json([
      {
        subdomain: "API",
        "function": "foo",
        param: req.param("bar")
      }
    ]);
  };

  controller.test = function(req, res) {
    console.log(req.body);
    return res.json([
      {
        subdomain: "API",
        "function": "test",
        body: req.body
      }
    ]);
  };

  controller.debug = function(req, res) {
    return res.json([
      {
        subdomain: "API",
        "function": "debug",
        req: util.inspect(req)
      }
    ]);
  };

  module.exports = controller;

}).call(this);

//# sourceMappingURL=hello.js.map
