// Generated by CoffeeScript 1.12.4
(function() {
  var controller;

  controller = {};

  controller.index = function(req, res) {
    return res.json("this is the API index");
  };

  module.exports = controller;

}).call(this);

//# sourceMappingURL=index.js.map
