// Generated by CoffeeScript 1.12.4
(function() {
  var RoutesGroupFactory, SubdomainsHandler, express,
    hasProp = {}.hasOwnProperty;

  express = require('express');

  SubdomainsHandler = require('../handlers/subdomain-handler.js');

  RoutesGroupFactory = {};

  RoutesGroupFactory.createRouter = function(file) {
    var router, routesConfig;
    routesConfig = require(file);
    router = {};
    router.registerRoutes = function(app) {
      var config, controllerFileName, controllerMethods, controllerRouter, error, i, key, len, middleware, middlewares, ref, ref1, ref2, ref3, route, routeGroupIndex, routes, routesController, routesGroup;
      routes = {};
      config = app.get('config');
      middlewares = app.get('middlewares');
      ref = routesConfig.routesGroups;
      for (routeGroupIndex in ref) {
        if (!hasProp.call(ref, routeGroupIndex)) continue;
        routesGroup = ref[routeGroupIndex];
        controllerFileName = routesGroup.controller;
        if (routes[routeGroupIndex] == null) {
          controllerRouter = express.Router();
          controllerMethods = require('../../' + config.appDir + '/' + routesConfig.controllerPath + '/' + controllerFileName);
          controllerRouter.controllerMethods = controllerMethods;
          routes[routeGroupIndex] = controllerRouter;
          routesController = routes[routeGroupIndex];
        }
        if ((ref1 = routesGroup.middlewares) != null ? ref1.length : void 0) {
          try {
            ref2 = routesGroup.middlewares;
            for (i = 0, len = ref2.length; i < len; i++) {
              middleware = ref2[i];
              routes[routeGroupIndex].use(middlewares[middleware]);
            }
          } catch (error1) {
            error = error1;
            console.log('Error registering middleware(s) for ' + controllerFileName);
            throw error;
          }
        }
        ref3 = routesGroup.routes;
        for (key in ref3) {
          if (!hasProp.call(ref3, key)) continue;
          route = ref3[key];
          try {
            routes[routeGroupIndex][route.method](route.url, routes[routeGroupIndex]['controllerMethods'][route.handler]);
          } catch (error1) {
            error = error1;
            console.log('Error registering route ' + route.handler + '.' + route.method);
            throw error;
          }
        }
        if (routesConfig.subdomain == null) {
          routesConfig.subdomain = '';
        }
        app.use(routesGroup.prefix, SubdomainsHandler.createRoutes(routesConfig.subdomain, routesController));
      }
      return true;
    };
    return router;
  };

  module.exports = RoutesGroupFactory;

}).call(this);

//# sourceMappingURL=router-factory.js.map
